### ISSUE TITLE
mobx-state-tree

### ISSUE THREAD

**Issue by joshua1** [NetanelBasal/ngx-mobx#1]
Hi @NetanelBasal  i came across your library and article, (on ajourney from ngxs store). i wanted to find out if this will work out of the box with mobx-state-tree (given that it is built on top of mobx)

**Comment by NetanelBasal** [comment]
I don't think so. I highly recommend you to consider using [Akita](https://netbasal.com/introducing-akita-a-new-state-management-pattern-for-angular-applications-f2f0fab5a8) instead.

**Comment by joshua1** [comment]
@NetanelBasal thanks for the suggestion. I did look at Akita and it shares a lot of concept with ngxs store which i have used. I would stick to using this library with mobx. I am hoping that this project hasn't been abandoned completely in favor of akita.
Thanks
